# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v
      - name: set up java 11
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: build with maven
        run: |
             mvn -B package --file Pom.xml
             mkdir artifacts cp target/*-jar artifacts
             cd artifacts && ls
      - name: save artifacts
        uses: actions/updload-artifact@v2
        with: 
         name:  github-action-artifact
         path: artifacts
        
        
        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
